language: node_js
node_js:
- node
- '11'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    - cmake
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.hunter"
script: npm run test
before_install: export CC=gcc-7; export CXX=g++-7
before_deploy:
- npm pack
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: evmc-*.tgz
  skip_cleanup: true
  on:
    branch: master
    node: '11'
    tags: true
- provider: npm
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  email: mwei@cs.ucsd.edu
  on:
    branch: master
    node: '11'
    tags: true
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs
  committer-from-gh: true
  on:
    branch: master
    node: '11'
env:
  global:
  - secure: b2swB7jtHzGeoSkvaBhCcSk7U3cV5Yl3tbB74N9sN1+6RZHnygjAjuC79GAgm3kqHU34k+fPk9e7BKNULDsPPszq+FzRMi1SZr5zu1V2b0lo/9HILKgBEvhovosWe7BWS7HYMGL3tdhsuKqdEyx9S0M1kd4+Sg6BSIRbXdcY3dxDSCNxEdlNijU7o+aiEH1Jvc8dDe11TEtaJ5jrAtA0wKJ3mU0jFNL4rkGZ+lAysuS2WH4W1XsA4Pa6jNm+eqxhXUKfUz5R2SssRGHh1XGwyalDsbtqV37mPYj+aIO8fnVs53ZOULNQT2b3tmX7aunsav2InXrm4Fl4lw0lGwR4TN7u/L8qLgByJANBKHvgu6DuBw3E12WN7JUDAxi1hRyV22mPVYdQr0mQhamO1E7h+HjHqs1nBnsLHzZFT0QnzYRFkOtqe9StNSCEJkTWmrQRCOAs+ixOohpsng+RkLjzBfhPHrhTvXtlyi7i9h3Q0NY/C/6KGOGPucP+2KiA+s79oeaojZx0RAhki4w6gGe3Bs228IkBGA+iICzU3w4bFjE8kV7NO9eDi4YoLOO06t7AR7XKGaclNVF0Tei+KU/XguPkteODFZZUY8xr+X0gmCksbbPeDvbAwrdX9pC3wBEyXF+XFHTnpmFTfknqMD15er9uoQQzXNTmL7CiH9EY3pk=
  - secure: oyFIWbVJovG+IW99J5f2nAXKxfJj1PPSh3WsG7Ua+2F7ztBsk3gUraJdujIZFRQLYF0qzSSQLR3ZHcqJOjS3UTw5bRWTAjCbjtfYzGhxQ9PXOhXepihmNIitplbfTIWTm2WY/DQDcfnbqgrzwqkghDFOn7JJAR/xB3VHefou2B3+5HLRFcirZ5hbX+avL2emt385Quf6chm48Vh7SkaUObLzWs2VclXRs9IKJ4Hk4tnlad2bGrI4Iuerf05oYNZuhgL3GP44ao8HIFjx02j2IwPashOHEgYmojQtZfYEDo4Xl9i1RSb3zLgrBpBAdxk2Mro0RRLpCkKIsXHWWM67QBzA3w+hcDyelTAhYgrhoXPKi6wHGLQm6/l7f+YgcEKLDwykI7Hj3gRNdYbFU/cXmWHwnpYPID3venxzC2jzMtZDj8nxByxxSvefxq5sF9iEForuefr9bOLaKL6if90Bk74F01SGowLF7tz8pDlOWOy0w14TNnzT5s4SQxHew0vyGmTxSDAsKXOA39dKNDEhzpqTPVKvvTadbW53jOXfQ0cOTN2hDD9Rb5Xf0UDrZ/ziPy76+q6Z0WDi0hfcFu2KZQyfLwnYvyMdPjqa2pey5yGTeRGpdNWOKSjnanxoiddWnOPOCR7Ytst2E+h1tsYJm1hkHIznBiJhiIK7NWP/W+I=
