dist: xenial
language: node_js
node_js:
- node
- '11'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.hunter"
script: npm run test
before_install: export CC=gcc-7; export CXX=g++-7
before_deploy:
- npm pack
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: evmc-*.tgz
  skip_cleanup: true
  on:
    branch: master
    node: '11'
    tags: true
- provider: npm
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  email: mwei@cs.ucsd.edu
  on:
    branch: master
    node: '11'
    tags: true
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs
  committer-from-gh: true
  on:
    branch: master
    node: '11'
env:
  global:
  - secure: RYVZcjQTX4Y8nkLvziVacPU2lKTRBrr3cFoVXk3JcH8xlLxOb9RUpDx6mqvtuvIbi3wa5ndAqKw+iAfwyriobgT37xtU3O6nZvTDFqkT84sY7+VP/ln8MtxObEezC5+3THNyL1BCnO2IyVSF328wvj3nH3vHKQqMdjJCINIC0lgt8Q1y4bhKgwZc9V3e/qHWU/YaTnPPVVxi6T3V+uS0xTFFQT5FdwQc65OrnC/4V0j2NEKb2WwzvpG9UjLacjLR8k3CVPYs/bjZEakmi2yyetQsbW4HcsHJB4/Utj1oiFI6O8e5D+IKjJRZXp1IZG0bFVMiOYDJgMlE73o5j3cRjQjNUvxZORPOgofqWrF8sySsERHWxn3HKRYx99H29XUMwnNmo+55MncdLURcA+M1yd9jwgVBJ7NE833iPX4Zu7pmPOlDeC530wNXu3GFWNGeBhvZNGQQtmXvE7rmYv9MQNpHn0t6SRoxmDyBLNsyKve+ATm7QiMQ1aOrpF3Qdw6uGop5QTbuMeJ7jvjKV9Y5vZFDurUev4j85kg8qhVwX2V7uz+eOQ95Ea6+vLbUnLkdUSx6tNLk1MsvZllXnGJDNtTtg5mVHePkhMCz8M2pBYVmBtnUed/+vfjx+s7r5E+MwPyfHtmW87h2viutau+KENzzHxUupT883V6Pfx9nvlA=
  - secure: Ms1kR9gw08pAjT38Uszk34mwnHFX895TRt5n96ZxQRlOMmWTpNqho4TliP6Bs4pJ2bFNz12W1weaxtOBtt3+0D+64UzFsqnRFn9uiw3CVuD0gdRxd9fMz0/kgdlUdaiyTgsf4nrQPZrS3YYj0erZLYYHwnDnciZ8cGWxU8rG1S4cFt6qSwiyGaQXC6OJwqPGfqiXUG9ApT5hw7CsgEeXGmBy6peY2LOs0EXcHVtrW4+pr6duxw36zB1GGBqdvheGQj9qwHHlG16iPMtj00rQ/0wuPGJHoq8kevJWH7ZCbPvjWKe55Jx6bKEmXyF+CKWs6psbWErn92VFaJqhXAoBnwuva4uvd8jWGudn8rG3TTKtkXzdwitS1H2WBsMI8LREDEskqRWMuA6BVg8h/IJbznd9Dd94I3QjeWdL5g1IXH72U8b0m0StmYQbghAGvQR+VsI5D3Lb4bwCz1xllaj68D4MvYveYmpnIhnGe7QGk4ZTFxz/R9pDPrMVsBueAqGqcTXt2RACNOOceyM4lsaHU4i4AtOidzVyMu5AAqJVYSS8BZwziFmkuJB83kthkAnnFYr4NFda6mNIvYhqADyE/OgI4Ka/NH476Ka13gLUChejNGMoZkEOn1vab5ae0J5D8DtVu3FUrkoOCQvKloDZRU1wH+IP69iQQQaFSPeEYUU=
